apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ssm-secret
spec:
  version: {{ .TagName }}
  homepage: https://github.com/pr8kerl/kubectl-ssm-secret
  shortDescription: Import/export secrets from/to AWS SSM param store
  description: |
    This plugin can import (create/update) a kubernetes secret with key/values 
    pairs stored at a single AWS SSM parameter store path. It can also export
    kubernetes secret data to an AWS SSM parameter store path. Finally, it can
    list secret keys/value pairs within a kubernetes secret or at an AWS SSM
    Parameter Store path.
spec:
  homepage: https://github.com/rajatjindal/kubectl-evict-pod
  platforms:
  - {{addURIAndSha "https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/{{ .TagName }}/kubectl-ssm-secret_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    sha256: fee332b178edd229d3c45c83f2a4c3b013b820cedfe5e73a69c0a99690c3bc61
    bin: kubectl-ssm_secret
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - {{addURIAndSha "https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/{{ .TagName }}/kubectl-ssm-secret_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-ssm_secret
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - {{addURIAndSha "https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/{{ .TagName }}/kubectl-ssm-secret_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-ssm_secret
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - {{addURIAndSha "https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/{{ .TagName }}/kubectl-ssm-secret_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-ssm_secret
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - {{addURIAndSha "https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/{{ .TagName }}/kubectl-ssm-secret_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-ssm_secret.exe
    selector:
      matchLabels:
        os: windows
        arch: amd64
