apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ssm-secret
spec:
  version: v1.3.0
  homepage: https://github.com/pr8kerl/kubectl-ssm-secret
  caveats: |
    Read the documentation at https://github.com/pr8kerl/kubectl-ssm-secret.
    You can call this plugin with "kubectl ssm-secret --help".
  shortDescription: Import/export secrets from/to AWS SSM param store
  description: |
    This plugin can import (create/update) a kubernetes secret with key/values 
    pairs stored at a single AWS SSM parameter store path. It can also export
    kubernetes secret data to an AWS SSM parameter store path. Finally, it can
    list secret keys/value pairs within a kubernetes secret or at an AWS SSM
    Parameter Store path.
  platforms:
  - uri: https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/v1.3.0/kubectl-ssm-secret_1.3.0_darwin_x86_64.tar.gz
    sha256: d19422a1d3300e1cbdb87ac7dfb5205f7452dcdfec33bfcc04677440e2cbd7a6
    bin: kubectl-ssm_secret
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - uri: https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/v1.3.0/kubectl-ssm-secret_1.3.0_linux_x86_64.tar.gz
    sha256: 611e13356a4031d0ccf005f2a9eb6174709e8e1dfed17ab7da96913bb5c5a3bf
    bin: kubectl-ssm_secret
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - uri: https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/v1.3.0/kubectl-ssm-secret_1.3.0_windows_x86_64.tar.gz
    sha256: 0c778b6f5fc6352be7c9e5cac7ec8a5231006ff8388d47ab61e82aa8a8f163b0
    bin: kubectl-ssm_secret.exe
    selector:
      matchLabels:
        os: windows
        arch: amd64

